# See: https://www.checkov.io/1.Welcome/Quick%20Start.html

compact: true
quiet: true
skip-path:
  - coverage
  - node_modules
skip-check:
  - CKV_GHA_7 # workflow_dispatch inputs for test scenarios are intentional
