# See: https://github.com/DavidAnson/markdownlint

# Unordered list style
MD004:
  style: dash

# Disable line length for tables
MD013:
  tables: false

# Ordered list item prefix
MD029:
  style: ordered  # Allow sequential numbering (1, 2, 3)

# Spaces after list markers
MD030:
  ul_single: 1
  ol_single: 1
  ul_multi: 1
  ol_multi: 1

# Allow inline HTML for details/summary/code elements
MD033:
  allowed_elements:
    - details
    - summary
    - code

# Code block language - disabled to allow language-less blocks
MD040: false

# Fenced code blocks surrounded by blank lines - disabled
MD031: false

# Code block style
MD046:
  style: fenced
