name: Changesets Publish Validator
description:
  Validate npm publishing prerequisites for changesets workflows (OIDC or
  token-based)
author: GarthDB

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: check-circle
  color: green

# Define your inputs here.
inputs:
  auth-method:
    description: 'Authentication method: "oidc" or "token"'
    required: true
  fail-on-error:
    description: 'Whether to fail the workflow on validation errors'
    required: false
    default: 'true'
  debug:
    description: 'Enable debug output with full environment info'
    required: false
    default: 'false'

# Define your outputs here.
outputs:
  valid:
    description: 'Whether validation passed (true/false)'

runs:
  using: node24
  main: dist/index.js
